namespace LundBot.Application.Common.Discord
{
    /// <summary>
    /// This is basically a clone of the one DSharpPlus has, but without giving a direct dependency on DSharpPlus.
    /// </summary>
    public enum DiscordPermissionEnum
    {
        CreateInvite = 0,
        KickMembers = 1,
        BanMembers = 2,
        Administrator = 3,
        ManageChannels = 4,
        ManageGuild = 5,
        AddReactions = 6,
        ViewAuditLog = 7,
        PrioritySpeaker = 8,
        Stream = 9,
        ViewChannel = 10,
        SendMessages = 11,
        SendTtsMessages = 12,
        ManageMessages = 13,
        EmbedLinks = 14,
        AttachFiles = 15,
        ReadMessageHistory = 16,
        MentionEveryone = 17,
        UseExternalEmojis = 18,
        ViewGuildInsights = 19,
        Connect = 20,
        Speak = 21,
        MuteMembers = 22,
        DeafenMembers = 23,
        MoveMembers = 24,
        UseVoiceActivity = 25,
        ChangeNickname = 26,
        ManageNicknames = 27,
        ManageRoles = 28,
        ManageWebhooks = 29,
        ManageGuildExpressions = 30,
        UseApplicationCommands = 31,
        RequestToSpeak = 32,
        ManageEvents = 33,
        ManageThreads = 34,
        CreatePublicThreads = 35,
        CreatePrivateThreads = 36,
        UseExternalStickers = 37,
        SendThreadMessages = 38,
        StartEmbeddedActivities = 39,
        ModerateMembers = 40,
        ViewCreatorMonetizationAnalytics = 41,
        UseSoundboard = 42,
        CreateGuildExpressions = 43,
        CreateEvents = 44,
        UseExternalSounds = 45,
        SendVoiceMessages = 46,
        SetVoiceChannelStatus = 48,
        SendPolls = 49,
        UseExternalApps = 50,
        PinMessages = 51,
        BypassSlowmode = 52,
    }
}
