services:
  bot:
    build:
      context: ./bot
    container_name: lundbot-discord
    restart: unless-stopped
    volumes:
      - ./bot:/app
      - /app/src/bin
      - /app/src/obj
    ports:
      - '3000:65535' # Web port
      - 5679:5678 # Debug port
    networks:
      - LundBotDiscordNetwork

networks:
  LundBotDiscordNetwork:
    driver: bridge
