services:
  bot:
    build:
      context: ./bot
    container_name: lundbot-discord
    restart: unless-stopped
    volumes:
      - ./bot/src/LundBot.Presentation/appsettings.json:/app/appsettings.json:ro
      - ./bot/src/LundBot.Presentation/appsettings.Production.json:/app/appsettings.Production.json:ro
      - ./bot/Logs:/app/Logs
    ports:
      - 3000:65535
    networks:
      - LundBotDiscordNetwork
    env_file:
      - .env
    profiles: ['Production']

  bot-dev:
    build:
      context: ./bot
    container_name: lundbot-discord-dev
    restart: unless-stopped
    volumes:
      - ./bot:/app:cached
    environment:
      DOTNET_CLI_HOME: /tmp/dotnet-home
      NUGET_PACKAGES: /tmp/nuget/packages
    ports:
      - 3000:65535
      - 5679:5678
    networks:
      - LundBotDiscordNetwork
    env_file:
      - .env
    profiles: ['Development']

  mariadb-dev:
    image: mariadb:11
    container_name: lundbot-mariadb-dev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'LundBotDiscord'
    volumes:
      - ./mariadb/dev-data:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - LundBotDiscordNetwork
    healthcheck:
      test: ['CMD', 'healthcheck.sh', '--connect', '--innodb_initialized']
      interval: 2s
      timeout: 5s
      retries: 10
      start_period: 5s
    profiles: ['Development']

networks:
  LundBotDiscordNetwork:
    driver: bridge

