<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>LundBot.Domain</RootNamespace>
  </PropertyGroup>

  <!-- Remove default logging -->
  <ItemGroup>
    <Using Remove="Microsoft.Extensions.Logging" />
  </ItemGroup>

</Project>
