<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>LundBot</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DSharpPlus" Version="4.5.3" />
    <PackageReference Include="DSharpPlus.Commands" Version="4.5.3" />
    <PackageReference Include="DSharpPlus.Interactivity" Version="4.5.3" />
    <!-- TODO: Probably have to remove SlashCommands, if it is no longer used. Ensure it is not used first -->
    <PackageReference Include="DSharpPlus.SlashCommands" Version="4.5.3" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="9.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.Newtonsoft" Version="10.2.3" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.18">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.18" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.18">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

</Project>
