// <auto-generated />
using System;
using LundBot.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LundBot.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LundBotDbContext))]
    partial class LundBotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("LundBot.Domain.Leaderboards.Leaderboard", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("LeaderboardsId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(3)")
                        .HasDefaultValueSql("UTC_TIMESTAMP(3)");

                    b.Property<ulong>("DiscordChannelId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("DiscordServerId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("LeaderboardType")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("LeaderboardType");

                    b.HasIndex("DiscordServerId", "DiscordChannelId")
                        .IsUnique()
                        .HasDatabaseName("leaderboards_index_2");

                    b.HasIndex("DiscordServerId", "LeaderboardType")
                        .HasDatabaseName("leaderboards_index_3");

                    b.ToTable("Leaderboards", (string)null);
                });

            modelBuilder.Entity("LundBot.Domain.Leaderboards.LeaderboardMessage", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("LeaderboardMessagesId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(3)")
                        .HasDefaultValueSql("UTC_TIMESTAMP(3)");

                    b.Property<ulong>("DiscordMessageId")
                        .HasColumnType("bigint unsigned");

                    b.Property<uint>("LeaderboardId")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.HasIndex("LeaderboardId")
                        .HasDatabaseName("IX_LeaderboardMessages_LeaderboardsId");

                    b.HasIndex("LeaderboardId", "DiscordMessageId")
                        .IsUnique()
                        .HasDatabaseName("LeaderboardMessages_index_2");

                    b.ToTable("LeaderboardMessages", (string)null);
                });

            modelBuilder.Entity("LundBot.Domain.Leaderboards.LeaderboardScore", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("LeaderboardScoreId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(3)")
                        .HasDefaultValueSql("UTC_TIMESTAMP(3)");

                    b.Property<ulong>("DiscordUserId")
                        .HasColumnType("bigint unsigned");

                    b.Property<uint>("LeaderboardId")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("Score")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(3)")
                        .HasDefaultValueSql("UTC_TIMESTAMP(3)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.HasKey("Id");

                    b.HasIndex("LeaderboardId")
                        .HasDatabaseName("IX_LeaderboardScore_LeaderboardsId");

                    b.HasIndex("DiscordUserId", "LeaderboardId")
                        .IsUnique()
                        .HasDatabaseName("LeaderboardScore_index_2");

                    b.ToTable("LeaderboardScores", (string)null);
                });

            modelBuilder.Entity("LundBot.Domain.Leaderboards.LeaderboardScoreSource", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("LeaderboardScoreSourceId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(3)")
                        .HasDefaultValueSql("UTC_TIMESTAMP(3)");

                    b.Property<ulong>("DiscordUserIdActor")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("DiscordUserIdTarget")
                        .HasColumnType("bigint unsigned");

                    b.Property<uint>("LeaderboardId")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.HasIndex("LeaderboardId")
                        .HasDatabaseName("IX_LeaderboardScoreSource_LeaderboardsId");

                    b.HasIndex("LeaderboardId", "DiscordUserIdActor", "DiscordUserIdTarget")
                        .HasDatabaseName("LeaderboardScoreSource_index_2");

                    b.ToTable("LeaderboardScoreSource", (string)null);
                });

            modelBuilder.Entity("LundBot.Domain.MemberJoin.MemberJoinMessage", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("MemberJoinMessageId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(3)")
                        .HasDefaultValueSql("UTC_TIMESTAMP(3)");

                    b.Property<ulong>("DiscordMessageId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("DiscordUserId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("DiscordUserId")
                        .IsUnique()
                        .HasDatabaseName("MemberJoinMessages_index_1");

                    b.ToTable("MemberJoinMessages", (string)null);
                });

            modelBuilder.Entity("LundBot.Domain.WebsiteTraffic.WebsiteTraffic", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("WebsiteTrafficId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<bool>("ClickedInviteButton")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(3)")
                        .HasDefaultValueSql("UTC_TIMESTAMP(3)");

                    b.Property<byte[]>("HashedIp")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.HasKey("Id");

                    b.HasIndex("HashedIp")
                        .IsUnique()
                        .HasDatabaseName("UniqueIp");

                    b.ToTable("WebsiteTraffic", (string)null);
                });

            modelBuilder.Entity("LundBot.Domain.WebsiteTraffic.WebsiteTrafficMessage", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("WebsiteTrafficMessageId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(3)")
                        .HasDefaultValueSql("UTC_TIMESTAMP(3)");

                    b.Property<ulong>("DiscordMessageId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("DiscordMessageId")
                        .IsUnique()
                        .HasDatabaseName("WebsiteTrafficMessage_index_1");

                    b.ToTable("WebsiteTrafficMessages", (string)null);
                });

            modelBuilder.Entity("LundBot.Domain.Leaderboards.LeaderboardMessage", b =>
                {
                    b.HasOne("LundBot.Domain.Leaderboards.Leaderboard", "Leaderboard")
                        .WithMany("LeaderboardMessages")
                        .HasForeignKey("LeaderboardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_leaderboard_messages_leaderboards");

                    b.Navigation("Leaderboard");
                });

            modelBuilder.Entity("LundBot.Domain.Leaderboards.LeaderboardScore", b =>
                {
                    b.HasOne("LundBot.Domain.Leaderboards.Leaderboard", "Leaderboard")
                        .WithMany("LeaderboardScores")
                        .HasForeignKey("LeaderboardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_leaderboard_scores_leaderboards");

                    b.Navigation("Leaderboard");
                });

            modelBuilder.Entity("LundBot.Domain.Leaderboards.LeaderboardScoreSource", b =>
                {
                    b.HasOne("LundBot.Domain.Leaderboards.Leaderboard", "Leaderboard")
                        .WithMany("LeaderboardScoreSources")
                        .HasForeignKey("LeaderboardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_leaderboard_score_source_leaderboards");

                    b.Navigation("Leaderboard");
                });

            modelBuilder.Entity("LundBot.Domain.Leaderboards.Leaderboard", b =>
                {
                    b.Navigation("LeaderboardMessages");

                    b.Navigation("LeaderboardScoreSources");

                    b.Navigation("LeaderboardScores");
                });
#pragma warning restore 612, 618
        }
    }
}
