@LundBot_HostAddress = http://localhost:3000
@command_id = 1234567890

### Unregister single command for global scope

DELETE {{LundBot_HostAddress}}/api/command/unregister/{{command_id}}?global=true
Accept: application/json

### Unregister  single command for all fast update guilds

DELETE {{LundBot_HostAddress}}/api/command/unregister/{{command_id}}?global=false
Accept: application/json

### Unregister all commands for global scope

DELETE {{LundBot_HostAddress}}/api/command/unregister/all?global=true
Accept: application/json

### Unregister all commands for all fast update guilds

DELETE {{LundBot_HostAddress}}/api/command/unregister/all?global=false
Accept: application/json