@LundBot_HostAddress = http://localhost:3000
@api_key = test
@Discord_ChannelId = 123456789012345678
@Discord_GuildId = 123456789012345678

POST {{LundBot_HostAddress}}/api/leaderboard/refresh?channelid={{Discord_ChannelId}}&guildid={{Discord_GuildId}}
Accept: application/json
Authorization: Bearer {{api_key}}