<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>Preview</LangVersion>

    <PackageId>DSharpPlus</PackageId>
    <Description>A C# API for Discord based off DiscordSharp, but rewritten to fit the API standards.</Description>
    <PackageTags>$(PackageTags), webhooks</PackageTags>

    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsPackable>true</IsPackable>

    <!-- Hide warnings -->
    <WarningLevel>0</WarningLevel>

    <!-- Disable .NET 10 built-in generators -->
    <DisableImplicitRegexGenerator>true</DisableImplicitRegexGenerator>
    <DisableImplicitLibraryImportGenerator>true</DisableImplicitLibraryImportGenerator>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.HighPerformance" Version="8.2.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.0" />

    <PackageReference Include="NetEscapades.EnumGenerators" Version="1.0.0-beta21" />

    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Polly.Core" Version="8.0.0" />
    <PackageReference Include="System.Threading.RateLimiting" Version="8.0.0" />
    <PackageReference Include="Ulid" Version="0.3.0" />
  </ItemGroup>

</Project>
