@LundBot_HostAddress = https://discord.lundbot69.com
@api_key = MWuxCLuzJGU4sidKs3uDFcWcnUYw0mOA9nZKpbvLYULLxKRNo8jT2HAoyjfa6XJCOlOc7BZ3L56ot3gcLi2JztzcYf3bNPOlCPc6TFcOSfnrRyNmN9dzi50LBKHBtsfL

GET {{LundBot_HostAddress}}/api/health
Accept: application/json
Authorization: Bearer {{api_key}}