// <auto-generated />
using System;
using LundBot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LundBot.Migrations
{
    [DbContext(typeof(LundBotDiscordDbContext))]
    partial class LundBotDiscordDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("LundBot.Entities.LeaderboardMessagesEntity", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("LeaderboardMessagesId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(3)")
                        .HasDefaultValueSql("UTC_TIMESTAMP(3)");

                    b.Property<string>("DiscordMessageId")
                        .IsRequired()
                        .HasColumnType("char(19)");

                    b.Property<uint>("LeaderboardsId")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.HasIndex("LeaderboardsId")
                        .HasDatabaseName("IX_LeaderboardMessages_LeaderboardsId");

                    b.HasIndex("LeaderboardsId", "DiscordMessageId")
                        .IsUnique()
                        .HasDatabaseName("LeaderboardMessages_index_2");

                    b.ToTable("LeaderboardMessages", (string)null);
                });

            modelBuilder.Entity("LundBot.Entities.LeaderboardScoreSourceEntity", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("LeaderboardScoreSourceId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(3)")
                        .HasDefaultValueSql("UTC_TIMESTAMP(3)");

                    b.Property<string>("DiscordUserIdActor")
                        .IsRequired()
                        .HasColumnType("char(19)");

                    b.Property<string>("DiscordUserIdTarget")
                        .IsRequired()
                        .HasColumnType("char(19)");

                    b.Property<uint>("LeaderboardsId")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.HasIndex("LeaderboardsId")
                        .HasDatabaseName("IX_LeaderboardScoreSources_LeaderboardsId");

                    b.HasIndex("LeaderboardsId", "DiscordUserIdActor", "DiscordUserIdTarget")
                        .HasDatabaseName("LeaderboardScoreSources_index_2");

                    b.ToTable("LeaderboardScoreSources", (string)null);
                });

            modelBuilder.Entity("LundBot.Entities.LeaderboardScoresEntity", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("LeaderboardScoresId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(3)")
                        .HasDefaultValueSql("UTC_TIMESTAMP(3)");

                    b.Property<string>("DiscordUserId")
                        .IsRequired()
                        .HasColumnType("char(19)");

                    b.Property<uint>("LeaderboardsId")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("Score")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(3)")
                        .HasDefaultValueSql("UTC_TIMESTAMP(3)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.HasKey("Id");

                    b.HasIndex("LeaderboardsId")
                        .HasDatabaseName("IX_LeaderboardScores_LeaderboardsId");

                    b.HasIndex("DiscordUserId", "LeaderboardsId")
                        .IsUnique()
                        .HasDatabaseName("LeaderboardScores_index_2");

                    b.ToTable("LeaderboardScores", (string)null);
                });

            modelBuilder.Entity("LundBot.Entities.LeaderboardsEntity", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("LeaderboardsId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(3)")
                        .HasDefaultValueSql("UTC_TIMESTAMP(3)");

                    b.Property<string>("DiscordChannelId")
                        .IsRequired()
                        .HasColumnType("char(19)");

                    b.Property<string>("DiscordServerId")
                        .IsRequired()
                        .HasColumnType("char(19)");

                    b.Property<string>("LeaderboardType")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("LeaderboardType");

                    b.HasIndex("DiscordServerId", "DiscordChannelId")
                        .IsUnique()
                        .HasDatabaseName("leaderboards_index_2");

                    b.HasIndex("DiscordServerId", "LeaderboardType")
                        .HasDatabaseName("leaderboards_index_3");

                    b.ToTable("Leaderboards", (string)null);
                });

            modelBuilder.Entity("LundBot.Entities.WebsiteTrafficEntity", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("WebsiteTrafficId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<bool>("ClickedInviteButton")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(3)")
                        .HasDefaultValueSql("UTC_TIMESTAMP(3)");

                    b.Property<byte[]>("HashedIp")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.HasKey("Id");

                    b.HasIndex("HashedIp")
                        .IsUnique()
                        .HasDatabaseName("UniqueIp");

                    b.ToTable("WebsiteTraffic", (string)null);
                });

            modelBuilder.Entity("LundBot.Entities.WebsiteTrafficMessagesEntity", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("WebsiteTrafficMessagesId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(3)")
                        .HasDefaultValueSql("UTC_TIMESTAMP(3)");

                    b.Property<string>("DiscordMessageId")
                        .IsRequired()
                        .HasColumnType("char(19)");

                    b.HasKey("Id");

                    b.HasIndex("DiscordMessageId")
                        .IsUnique()
                        .HasDatabaseName("WebsiteTrafficMessages_index_1");

                    b.ToTable("WebsiteTrafficMessages", (string)null);
                });

            modelBuilder.Entity("LundBot.Entities.WelcomeMessageEntity", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("WelcomeMessagesId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(3)")
                        .HasDefaultValueSql("UTC_TIMESTAMP(3)");

                    b.Property<string>("DiscordMessageId")
                        .IsRequired()
                        .HasColumnType("char(19)");

                    b.Property<string>("DiscordUserId")
                        .IsRequired()
                        .HasColumnType("char(19)");

                    b.HasKey("Id");

                    b.HasIndex("DiscordUserId")
                        .IsUnique()
                        .HasDatabaseName("WelcomeMessages_index_1");

                    b.ToTable("WelcomeMessages", (string)null);
                });

            modelBuilder.Entity("LundBot.Entities.LeaderboardMessagesEntity", b =>
                {
                    b.HasOne("LundBot.Entities.LeaderboardsEntity", "Leaderboard")
                        .WithMany("LeaderboardMessages")
                        .HasForeignKey("LeaderboardsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_leaderboard_messages_leaderboards");

                    b.Navigation("Leaderboard");
                });

            modelBuilder.Entity("LundBot.Entities.LeaderboardScoreSourceEntity", b =>
                {
                    b.HasOne("LundBot.Entities.LeaderboardsEntity", "Leaderboard")
                        .WithMany("LeaderboardScoreSources")
                        .HasForeignKey("LeaderboardsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_leaderboard_score_sources_leaderboards");

                    b.Navigation("Leaderboard");
                });

            modelBuilder.Entity("LundBot.Entities.LeaderboardScoresEntity", b =>
                {
                    b.HasOne("LundBot.Entities.LeaderboardsEntity", "Leaderboard")
                        .WithMany("LeaderboardScores")
                        .HasForeignKey("LeaderboardsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_leaderboard_scores_leaderboards");

                    b.Navigation("Leaderboard");
                });

            modelBuilder.Entity("LundBot.Entities.LeaderboardsEntity", b =>
                {
                    b.Navigation("LeaderboardMessages");

                    b.Navigation("LeaderboardScoreSources");

                    b.Navigation("LeaderboardScores");
                });
#pragma warning restore 612, 618
        }
    }
}
